### ISSUE TITLE
Throws error upon attempting to open.

### ISSUE THREAD

**Issue by Kalrell** [xivapi/SaintCoinach#165]
Hi you probably already working on this, I just tried with the update 50 mins ago, but still seem to have this error message.

Unhandled Exception: System.IO.DirectoryNotFoundException: Attempted to access a path that is not on the disk.
   at SaintCoinach.IO.PackCollection..ctor(DirectoryInfo dataDirectory) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\IO\PackCollection.cs:line 30
   at SaintCoinach.ARealmReversed..ctor(DirectoryInfo gameDirectory, FileInfo storeFile, Language language, FileInfo libraFile) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\ARealmReversed.cs:line 196
   at SaintCoinach.ARealmReversed..ctor(String gamePath, String storePath, Language language, String libraPath) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\ARealmReversed.cs:line 180
   at SaintCoinach.Cmd.Program.Main(String[] args) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach.Cmd\Program.cs:line 40

**Comment by Supamiu** [comment]
The error is quite explaining everything, the directory for which your instance is configured cannot be found.

**Comment by CrimsonOrion** [comment]
Patch number needs to be updated
