### ISSUE TITLE
System.OutOfMemoryException: Could not execute function after 5 attempts while trying to update

### ISSUE THREAD

**Issue by Nerothos** [xivapi/SaintCoinach#26]
Hello, while I try to update the definitions with the last patch, I get a OOM exception.

```
Game version: 2021.08.17.0000.0000
Definition version: 2021.07.15.0000.0000
Update is available, perform update (Y/n)? y
  0% (0 / 1284): Structure > Achievement
....
 99% (1268 / 1284): Data > ENpcResident

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Could not execute function after 5 attempts.
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.MemoryGuard[T](Func`1 func) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 148
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.<>c__DisplayClass13_0.<Update>b__1(SheetDefinition prevSheetDef) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 121
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.Update(Boolean detectDataChanges) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 103
   at SaintCoinach.ARealmReversed.Update(Boolean detectDataChanges, IProgress`1 progress) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\ARealmReversed.cs:line 382
   at SaintCoinach.Cmd.Program.Main(String[] args) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach.Cmd\Program.cs:line 50
```

Process memory sit around 3.3-3.5GB, I got plenty memory available.

Happen with other elements :

```
 99% (1268 / 1284): Data > ActionProcStatus
```
or  
```
98% (1263 / 1284): Data > ActionCastTimeline
```
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Could not execute function after 5 attempts.
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.MemoryGuard[T](Func`1 func) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 148
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.<>c__DisplayClass13_0.<Update>b__1(SheetDefinition prevSheetDef) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 121
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SaintCoinach.Ex.Relational.Update.RelationUpdater.Update(Boolean detectDataChanges) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\Ex\Relational\Update\RelationUpdater.cs:line 103
   at SaintCoinach.ARealmReversed.Update(Boolean detectDataChanges, IProgress`1 progress) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach\ARealmReversed.cs:line 382
   at SaintCoinach.Cmd.Program.Main(String[] args) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach.Cmd\Program.cs:line 50
```

I'm not sure if it's linked to #23 ? I tried with powershell 64 bits but obviously that didn't change much.
The memory doesn't seems to be emptied after each element, maybe that's a trail to follow?

**Comment by IcarusTwine** [comment]
You shouldnt need to perform an update, that's been borked for a while now, I'll be home in an hour, if no ones fixed it then I'll make a pr

**Comment by Nerothos** [comment]
I'm not forced to do the update, I can say No to it, but that's what happen if I try to do an update.

**Comment by IcarusTwine** [comment]
https://github.com/xivapi/SaintCoinach/pull/27
that should fix it, really the "update" function is just a way to check what was changed but it hasnt been working right for a while now

**Comment by quisquous** [comment]
I know you have closed this, but I get this constantly whenever I try to update, both historically in the past, and also with the latest version against the latest patch.  If I run it like 30 times, it sometimes will eventually work.
